### ISSUE TITLE
libdigiapix fails to build with libgpiod v2 (X-LINUX-AI / DEY 5.0 integration)

### ISSUE THREAD

**Issue by 1saeed** [digi-embedded/libdigiapix#2]
When building DEY 5.0 (ccmp25-dvk) with ST’s X-LINUX-AI package group enabled, libgpiod is upgraded to the v2 API. libdigiapix still targets the legacy v1 symbols (gpiod_chip_open_lookup, struct gpiod_line_request_config, gpiod_line_request_*, etc.), so the recipe fails at do_compile.

```
src/gpio.c:447:24: error: variable 'request_cfg' has initializer but incomplete type
  447 |                 struct gpiod_line_request_config request_cfg = { 0 };
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
src/gpio.c:451:44: error: 'GPIOD_LINE_REQUEST_DIRECTION_AS_IS' undeclared
src/gpio.c:454:46: error: 'GPIOD_LINE_REQUEST_FLAG_ACTIVE_LOW' undeclared
...
src/gpio.c:472:52: error: 'GPIOD_LINE_REQUEST_EVENT_FALLING_EDGE' undeclared
src/gpio.c:498:23: error: implicit declaration of function 'gpiod_line_request'
```
Reproduction steps

1. Use Digi Embedded Yocto 5.0 (ccmp25-dvk) shell environment.
2. Add ST’s AI tooling to the image:
```
IMAGE_INSTALL:append = " tensorflow-lite onnxruntime packagegroup-x-linux-ai"
   (`packagegroup-x-linux-ai` depends on libgpiod v2.)
```
3. `bitbake core-image-base`
4. Observe `libdigiapix` failure during `do_compile`.

Could you provide an official patch or new release of libdigiapix that builds against libgpiod v2? That would let us include ST’s X-LINUX-AI packages without downgrading gpiod locally.
Thanks!

**Comment by jviguera** [comment]
Should be fixed in commit:

https://github.com/digi-embedded/meta-digi/commit/8625756a2b827e3bc42c823eaa1df01dc7c88396

You need to update with "repo sync".
